const descriptionsList = [
  'FULL LOCKUPS | ICONIC MARKS | WORDMARKS',
  'SPLASH PAGES | SQUARESPACE SITES | CUSTOM WEBSITES',
  'BRAND DECKS | CAPABILITIES DECKS | INVESTOR DECKS | MARKETING PLANS',
  'DIGITAL POSTERS | BANNERS | COLLAGES | ALBUM & FILM/TV ART',
  'BRAND IDENTITY DEVELOPMENT | STYLE GUIDELINES | TYPOGRAPHY',
  'STRATEGY | IDEATION & CONCEPTION | COMMUNICATION  ',
  'SOCIAL MEDIA STRATEGY | GRAPHICS CREATION | MANAGEMENT',
  'NEWSLETTERS | BIZ CARDS | BROCHURES',
  'RFP RESPONSES | NEW BIZ DECKS | CUSTOM TEMPLATES',
]

export default descriptionsList
